# :schema: https://www.schemastore.org/prek.json

[[repos]]
repo = "builtin"
hooks = [
    { id = "trailing-whitespace" },
    { id = "end-of-file-fixer" },
    { id = "check-added-large-files" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.0"
hooks = [
    { id = "ruff-check", args = ["--fix"], types_or = ["python", "pyi"] },
    { id = "ruff-format", types_or = ["python", "pyi"] },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id             = "mise format"
name           = "mise format"
entry          = "mise run format"
language       = "system"
pass_filenames = false
