[buildings]
yeonseo     = '01연서도서관'
cheolsan    = '02철산어린이집'
kepco_paju  = '03한전파주'
yecheon_gov = '04예천청사'
neulpum     = '05늘품유치원'
kea         = '06KEA'
keit        = '07KEIT'
gcea        = '08GCEA'
kiria       = '09KIRIA'
energyx     = '10EnergyX'
